import DepartmentManage from "./DepartmentManage/DepartmentManage"

export {default as Home} from "./Home/Home"
export {default as Main} from "./Main/Main"
export {default as CompanyManage} from "./CompanyManage/CompanyManage"
export {default as CompanyDetail} from "./CompanyManage/CompanyDetail"
export {default as Login} from "./Login/Login"
export {default as DepartmentManage } from "./DepartmentManage/DepartmentManage"
export {default as EmployeeListManage } from "./EmployeeListManage/EmployeeListManage"
export {default as EmployeeManage } from "./EmployeeManage/EmployeeManage"
export {default as AnnualManage } from "./AnnualManage/AnnualManage"
export {default as AttendanceManage } from "./AttendanceManage/AttendanceManage"
export {default as WorkTimeManage } from "./WorkTimeManage/WorkTimeManage"
export {default as PayrollManage } from "./PayrollManage/PayrollManage"
export {default as RateManage } from "./RateManage/RateManage"
export {default as PayrollCheck } from "./PayrollManage/PayrollCheck"
export {default as TransferHistory } from "./TransferHistory/TransferHistory"
export {default as DepartureInsurance } from "./DepartureInsurance/DepartureInsurance"
export {default as RetirePension } from "./RetirePension/RetirePension"
export {default as InsuranceClaim } from "./InsuranceClaim/InsuranceClaim"
export {default as DeviceManage } from "./DeviceManage/DeviceManage"