export {default as IconInput} from "./IconInput/IconInput"
export {default as Footer} from "./Footer/Footer"
export {default as SideNav} from "./SideNav/SideNav"
export {default as Header} from "./Header/Header"
export {default as CompanyDetailTable} from "./Table/CompanyDetailTable"
export {default as EmployeeTable} from "./Table/EmployeeTable"
export {default as EmployeeListTable} from "./Table/EmployeeListTable"